version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3.8.9-management'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
