spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  mustache:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true